### ISSUE TITLE
Device enumeration failed Unkown error: HTTP(128090832): 

### ISSUE THREAD

**Issue by PiecePaperCode** [sbencoding/wdfs#11]
**Have you checked already existing issues and none match the problem you're having?**
Yes

**Describe the bug**
```sh
**$** '/home/ubuntu/device_locator' 'EMAIL 'PASSWORD'
Enumerating devices... please wait!
Unkown error: HTTP(128090832): 

Device enumeration failed
```

**To Reproduce**
compile on multipass VM ubuntu 20.04LTS make fs dosent work
Make Sure WD Cloud Home is on the same Network
```
g++ ../src/device_locator.cpp ../src/wdfs.cpp ../src/bridge.cpp -o ../bin/device_locator `pkg-config fuse3 --cflags --libs && curl-config --libs`
```
launch locator application

**Expected behavior**
my enumerated devices

**Desktop (please complete the following information):**
 - Distro: ubuntu 20.04LTS and 20.10
 - curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

 - Linux wdfs 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sbencoding** [comment]
Hey!
So WD decided to move their device enumeration to a new host and for this reason the server at the original URL was unavailable.
Another bug was that the status code wasn't properly parsed, because it should have printed the 503 error that the server returned.

Anyways bug fixed and URL updated to the new one in https://github.com/sbencoding/wdfs/commit/9f094b504e5e5edc1ef6bb4e05c91e71aead095a so it should work now.

As a side note, and for future reference the device locator should work even if you aren't in the same network as the device, though the actual fs only supports local devices as of currently.

Thank you for reporting the issue and please comment whether or not the fix has worked for you!

**Comment by PiecePaperCode** [comment]
re cloned the repo and build it again

Enumerating devices... please wait!
Listing devices for user:
[0] My Cloud Home Duo (My Device Number)

it works.
It also works when the device is not connected to the internet and is offline. The Server responds fine now.
